In [1]:
import pandas as pd

In [2]:
# import files
education = pd.read_excel("Education.xlsx")
poverty = pd.read_excel("PovertyEstimates.xlsx")
unemployment = pd.read_excel("Unemployment.xlsx")

In [3]:
#change files to data frame
education_df = pd.DataFrame(education)
#education.head()
#print(list(education_df.columns))

poverty_df = pd.DataFrame(poverty)
#poverty_df.head()
#print(list(poverty_df.columns))

unemployment_df = pd.DataFrame(unemployment)
#unemployment_df.head()
#print(list(unemployment_df.columns))

In [4]:
#clean data frame to keep only relevant data
education_columns = ["State", "Area name", "Less than a high school diploma, 2017-21", "High school diploma only, 2017-21", "Some college or associate's degree, 2017-21",
                    "Bachelor's degree or higher, 2017-21", "Percent of adults with less than a high school diploma, 2017-21",
                    "Percent of adults with a high school diploma only, 2017-21", "Percent of adults completing some college or associate's degree, 2017-21",
                    "Percent of adults with a bachelor's degree or higher, 2017-21"]
education_data = education_df[education_columns].copy()

education_data = education_data.drop(education_data[education_data["State"] == "PR"].index)
education_data.drop_duplicates(subset=["Area name", "State"], inplace=True)
education_data.dropna(inplace=True)
education_data = education_data[education_data['Area name'].str.contains('County')]

education_data = education_data.reset_index(drop=True)
education_data

,State,Area name,"Less than a high school diploma, 2017-21","High school diploma only, 2017-21","Some college or associate's degree, 2017-21","Bachelor's degree or higher, 2017-21","Percent of adults with less than a high school diploma, 2017-21","Percent of adults with a high school diploma only, 2017-21","Percent of adults completing some college or associate's degree, 2017-21","Percent of adults with a bachelor's degree or higher, 2017-21"
0,AL,Autauga County,4126.0,12977.0,11367.0,11144.0,10.415510,32.758621,28.694401,28.131469
1,AL,Baldwin County,14555.0,44342.0,50518.0,52562.0,8.985844,27.375492,31.188379,32.450286
2,AL,Barbour County,4378.0,6600.0,5010.0,2007.0,24.328980,36.676855,27.841067,11.153098
3,AL,Bibb County,3125.0,7052.0,3967.0,1913.0,19.461917,43.918540,24.705736,11.913807
4,AL,Blount County,6650.0,14284.0,13673.0,6061.0,16.351923,35.123439,33.621029,14.903610
...,...,...,...,...,...,...,...,...,...,...
3002,WY,Sweetwater County,2029.0,9069.0,11324.0,5394.0,7.294363,32.603538,40.710383,19.391717
3003,WY,Teton County,701.0,2984.0,3755.0,10219.0,3.969647,16.897899,21.263945,57.868509
3004,WY,Uinta County,851.0,4820.0,5186.0,2376.0,6.430892,36.424091,39.189904,17.955112
3005,WY,Washakie County,320.0,1391.0,2293.0,1419.0,5.900793,25.650009,42.282869,26.166329
3006,WY,Weston County,348.0,1826.0,1818.0,900.0,7.113655,37.326247,37.162715,18.397383

In [5]:
# clean data frame to keep only relevant data
poverty_columns = ["Stabr", "Area_name", "POVALL_2020", "PCTPOVALL_2020"]
poverty_data = poverty_df[poverty_columns].copy()

# rename columns to be more readable
poverty_data = poverty_data.rename(columns={"Stabr": "State", "Area_name": "Area name", "POVALL_2020": "Estimate of people of all ages in poverty 2020",
                                            "PCTPOVALL_2020": "Estimated percent of people of all ages in poverty 2020"})

poverty_data = poverty_data.drop(poverty_data[poverty_data["State"] == "PR"].index)
poverty_data.drop_duplicates(subset=["Area name", "State"], inplace=True)
poverty_data = poverty_data[poverty_data['Area name'].str.contains('County')]

poverty_data = poverty_data.reset_index(drop=True)
poverty_data

,State,Area name,Estimate of people of all ages in poverty 2020,Estimated percent of people of all ages in poverty 2020
0,AL,Autauga County,6242.0,11.2
1,AL,Baldwin County,20189.0,8.9
2,AL,Barbour County,5548.0,25.5
3,AL,Bibb County,3549.0,17.8
4,AL,Blount County,7525.0,13.1
...,...,...,...,...
3002,WY,Sweetwater County,3187.0,7.6
3003,WY,Teton County,1207.0,5.2
3004,WY,Uinta County,1697.0,8.5
3005,WY,Washakie County,739.0,9.7
3006,WY,Weston County,679.0,10.6

In [6]:
#clean data frame to keep only relevant data
unemployment_columns = ["State", "Area_name", "Employed_2020", "Unemployed_2020", "Unemployment_rate_2020",
                        "Median_Household_Income_2020", "Med_HH_Income_Percent_of_State_Total_2020"]


unemployment_data = unemployment_df[unemployment_columns].copy()
#unemployment_data.head()

# rename columns to be more readable
unemployment_data = unemployment_data.rename(columns={"Area_name": "Area name", "Med_HH_Income_Percent_of_State_Total_2020": 
                                                    "County household median income as a percent of the State total median household income, 2020"})

unemployment_data = unemployment_data.drop(unemployment_data[unemployment_data["State"] == "PR"].index)
unemployment_data.drop_duplicates(subset=["Area name", "State"], inplace=True)
unemployment_data.dropna(inplace=True)
unemployment_data = unemployment_data[unemployment_data['Area name'].str.contains('County')]

unemployment_data = unemployment_data.reset_index(drop=True)
unemployment_data

,State,Area name,Employed_2020,Unemployed_2020,Unemployment_rate_2020,Median_Household_Income_2020,"County household median income as a percent of the State total median household income, 2020"
0,AL,"Autauga County, AL",24985.0,1420.0,5.4,67565.0,125.217762
1,AL,"Baldwin County, AL",92751.0,6159.0,6.2,71135.0,131.834019
2,AL,"Barbour County, AL",8004.0,676.0,7.8,38866.0,72.030097
3,AL,"Bibb County, AL",8073.0,639.0,7.3,50907.0,94.345602
4,AL,"Blount County, AL",23973.0,1143.0,4.6,55203.0,102.307350
...,...,...,...,...,...,...,...
3001,WY,"Sweetwater County, WY",18998.0,1505.0,7.3,70583.0,104.903097
3002,WY,"Teton County, WY",14251.0,887.0,5.9,92488.0,137.459128
3003,WY,"Uinta County, WY",8532.0,570.0,6.3,71246.0,105.888473
3004,WY,"Washakie County, WY",3739.0,206.0,5.2,58532.0,86.992450
3005,WY,"Weston County, WY",3645.0,144.0,3.8,58901.0,87.540872

In [7]:
#clean data
education_data.columns = education_data.columns.str.title()
poverty_data.columns = poverty_data.columns.str.title()
unemployment_data.columns = unemployment_data.columns.str.title()
education_data.columns = education_data.columns.str.strip()
poverty_data.columns = poverty_data.columns.str.strip()
unemployment_data.columns = unemployment_data.columns.str.strip()


education_data = education_data.reset_index(drop=True)
poverty_data = poverty_data.reset_index(drop=True)
unemployment_data = unemployment_data.reset_index(drop=True)

all_data = pd.concat([education_data, poverty_data, unemployment_data], axis=1, join="outer").reindex(education_data.index)
all_data = all_data.loc[:, ~all_data.columns.duplicated()]
all_data = all_data.dropna()
all_data

,State,Area Name,"Less Than A High School Diploma, 2017-21","High School Diploma Only, 2017-21","Some College Or Associate'S Degree, 2017-21","Bachelor'S Degree Or Higher, 2017-21","Percent Of Adults With Less Than A High School Diploma, 2017-21","Percent Of Adults With A High School Diploma Only, 2017-21","Percent Of Adults Completing Some College Or Associate'S Degree, 2017-21","Percent Of Adults With A Bachelor'S Degree Or Higher, 2017-21",Estimate Of People Of All Ages In Poverty 2020,Estimated Percent Of People Of All Ages In Poverty 2020,Employed_2020,Unemployed_2020,Unemployment_Rate_2020,Median_Household_Income_2020,"County Household Median Income As A Percent Of The State Total Median Household Income, 2020"
0,AL,Autauga County,4126.0,12977.0,11367.0,11144.0,10.415510,32.758621,28.694401,28.131469,6242.0,11.2,24985.0,1420.0,5.4,67565.0,125.217762
1,AL,Baldwin County,14555.0,44342.0,50518.0,52562.0,8.985844,27.375492,31.188379,32.450286,20189.0,8.9,92751.0,6159.0,6.2,71135.0,131.834019
2,AL,Barbour County,4378.0,6600.0,5010.0,2007.0,24.328980,36.676855,27.841067,11.153098,5548.0,25.5,8004.0,676.0,7.8,38866.0,72.030097
3,AL,Bibb County,3125.0,7052.0,3967.0,1913.0,19.461917,43.918540,24.705736,11.913807,3549.0,17.8,8073.0,639.0,7.3,50907.0,94.345602
4,AL,Blount County,6650.0,14284.0,13673.0,6061.0,16.351923,35.123439,33.621029,14.903610,7525.0,13.1,23973.0,1143.0,4.6,55203.0,102.307350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001,WY,Sublette County,303.0,1969.0,2206.0,1623.0,4.966399,32.273398,36.158007,26.602196,610.0,6.2,18998.0,1505.0,7.3,70583.0,104.903097
3002,WY,Sweetwater County,2029.0,9069.0,11324.0,5394.0,7.294363,32.603538,40.710383,19.391717,3187.0,7.6,14251.0,887.0,5.9,92488.0,137.459128
3003,WY,Teton County,701.0,2984.0,3755.0,10219.0,3.969647,16.897899,21.263945,57.868509,1207.0,5.2,8532.0,570.0,6.3,71246.0,105.888473
3004,WY,Uinta County,851.0,4820.0,5186.0,2376.0,6.430892,36.424091,39.189904,17.955112,1697.0,8.5,3739.0,206.0,5.2,58532.0,86.992450
3005,WY,Washakie County,320.0,1391.0,2293.0,1419.0,5.900793,25.650009,42.282869,26.166329,739.0,9.7,3645.0,144.0,3.8,58901.0,87.540872

In [8]:
#output all data into csv
all_data.to_csv("C:\\Users\\ginav\\Desktop\\Analysis Projects\\Project 1\\all_data.csv", index=False)